### ISSUE TITLE
FEATURE : 서비스 로직을 위한 레파지토리를 개발한다.

### ISSUE THREAD

**Issue by ohinhyuk** [Impactive-AI-Dev/Impactive-AI-Back#19]
## Description

서비스 단에서 사용할 쿼리를 위한 JPA 레파지토리를 개발한다.
DATA JPA를 사용하기 때문에 인터페이스를 작성한다.

## ToDo

- [x] Project 레파지토리 개발
- [x] Random_Word 레파지토리 개발
- [x] User 레파지토리 개발
- [x] Idea 레파지토리 개발
