### ISSUE TITLE
FEATURE : 상세 아이디어를 생성 및 단일 조회할 수 있다.

### ISSUE THREAD

**Issue by ohinhyuk** [Impactive-AI-Dev/Impactive-AI-Back#25]
## Description

아이디어를 통해 상세 아이디어를 생성한다.
상세 아이디어 목록에서 상세 아이디어를 단일 조회 한다.

상세 아이디어 id와 프로젝트 id를 쿼리 스트링으로 넘기면
해당 상세 아이디어에 대한 정보와 다른 상세 아이디어들의 간략한 정보 ()를 리스트로 보내준다.

## ToDo
- [x] 상세 아이디어 생성 서비스 구현
- [x] 상세 아이디어 생성 API 구현
- [x] 상세 아이디어를 조회 하는 서비스를 구현
- [x] 상세 아이디어를 조회 하는 API 구현
- [x] 테스트 코드를 통해 확인
