### ISSUE TITLE
FEATURE : 검색 키워드를 조회/저장/삭제를 구현 하여 사용자가 최근 사용한 검색어를 관리할 수 있다.

### ISSUE THREAD

**Issue by ohinhyuk** [Impactive-AI-Dev/Impactive-AI-Back#31]
## Description

최근 검색 키워드를 저장하고 최근 사용한 순으로 불러올 수 있다.
검색 할 시에 검색 키워드 저장 API를 호출하여 검색 결과를 저장한다.
메인 페이지에서 검색 키워드들을 최근 사용한 순으로 불러 온다.

## ToDo

- [x] 검색 키워드 조회
- [x] 검색 키워드 저장
- [x] 검색 키워드 삭제
